CREATE TABLE USUARIO
(
 id SERIAL PRIMARY KEY,
 nome VARCHAR(100) NOT NULL,
 email VARCHAR(100) NOT NULL,
 senha VARCHAR(100) NOT NULL,
 perfil_id INT,
 UNIQUE (email)
);

CREATE TABLE ARTISTA
(
 id SERIAL PRIMARY KEY,
 nome VARCHAR(100) NOT NULL,
 bio TEXT,
 fotoUrl VARCHAR(100)
);

CREATE TABLE ALBUM
(
 id SERIAL PRIMARY KEY,
 titulo VARCHAR(100) NOT NULL,
 capaUrl VARCHAR(100),
 dataLancamento DATE,
 artista_id INT NOT NULL
);

CREATE TABLE MUSICA
(
 id SERIAL PRIMARY KEY,
 deezerId VARCHAR(100),
 titulo VARCHAR(100) NOT NULL,
 duracao INT NOT NULL,
 previewUrl VARCHAR(100),
 capaUrl VARCHAR(100),
 genero VARCHAR(100) NOT NULL,
 album_id INT,
 UNIQUE (deezerId)
);

CREATE TABLE PLAYLIST
(
 id SERIAL PRIMARY KEY,
 nome VARCHAR(100) NOT NULL,
 publica BOOLEAN NOT NULL,
 dataCriacao TIMESTAMP NOT NULL,
 usuario_id INT
);

CREATE TABLE PLAYLIST_MUSICA
(
 playlist_id INT,
 musica_id INT,
 ordem INT,
 PRIMARY KEY (playlist_id, musica_id)
);

CREATE TABLE FAVORITO
(
 id SERIAL PRIMARY KEY,
 usuario_id INT NOT NULL,
 musica_id INT,
 dataFavoritado TIMESTAMP NOT NULL
);

CREATE TABLE HISTORICO_EXECUCAO
(
 id SERIAL PRIMARY KEY,
 usuario_id INT NOT NULL,
 musica_id INT NOT NULL,
 dataHoraExecucao TIMESTAMP NOT NULL,
 tempoOuvido INT
);

CREATE TABLE LOG_AUDITORIA
(
 id SERIAL PRIMARY KEY,
 usuario_id INT,
 acao VARCHAR(100) NOT NULL,
 descricao VARCHAR(100),
 dataHora TIMESTAMP NOT NULL
);

CREATE TABLE PERFIL
(
 id SERIAL PRIMARY KEY,
 nome VARCHAR(100) NOT NULL,
 UNIQUE (nome)
);

ALTER TABLE USUARIO ADD FOREIGN KEY(perfil_id) REFERENCES PERFIL (id);
ALTER TABLE ALBUM ADD FOREIGN KEY(artista_id) REFERENCES ARTISTA (id);
ALTER TABLE MUSICA ADD FOREIGN KEY(album_id) REFERENCES ALBUM (id);
ALTER TABLE PLAYLIST ADD FOREIGN KEY(usuario_id) REFERENCES USUARIO (id);
ALTER TABLE PLAYLIST_MUSICA ADD FOREIGN KEY(playlist_id) REFERENCES PLAYLIST (id);
ALTER TABLE PLAYLIST_MUSICA ADD FOREIGN KEY(musica_id) REFERENCES MUSICA (id);
ALTER TABLE FAVORITO ADD FOREIGN KEY(usuario_id) REFERENCES USUARIO (id);
ALTER TABLE FAVORITO ADD FOREIGN KEY(musica_id) REFERENCES MUSICA (id);
ALTER TABLE HISTORICO_EXECUCAO ADD FOREIGN KEY(usuario_id) REFERENCES USUARIO (id);
ALTER TABLE HISTORICO_EXECUCAO ADD FOREIGN KEY(musica_id) REFERENCES MUSICA (id);
ALTER TABLE LOG_AUDITORIA ADD FOREIGN KEY(usuario_id) REFERENCES USUARIO (id);
