spring.application.name=Deefy

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/deefy}

spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
jwt.expiration=${JWT_EXPIRATION:86400000}


# CONFIGURAÇÃO DO SPRING MAIL

spring.mail.host=smtp.gmail.com
spring.mail.port=587


spring.mail.username=${DEEFY_EMAIL_USER:seu_email_aqui@gmail.com}
spring.mail.password=${DEEFY_EMAIL_PASS:sua_senha_de_app_aqui}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Tempo de vida do token de redefinição (15 minutos = 900000 ms)
jwt.password.reset.expiration=900000